// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZV6tK5fUsYoZKjm9w7bBVUDiV87sfxA',
    appId: '1:877353420115:web:43f169d47b2c0361574da6',
    messagingSenderId: '877353420115',
    projectId: 'task-app-f70e1',
    authDomain: 'task-app-f70e1.firebaseapp.com',
    storageBucket: 'task-app-f70e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6D7qjhwMlejHxQCzMxktu8y17bcvDEVE',
    appId: '1:877353420115:android:a511663128639598574da6',
    messagingSenderId: '877353420115',
    projectId: 'task-app-f70e1',
    storageBucket: 'task-app-f70e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPBhuSlANGO8n9h6pPkMte8OBF9QbJ_s',
    appId: '1:877353420115:ios:03514e63a6eb6ce2574da6',
    messagingSenderId: '877353420115',
    projectId: 'task-app-f70e1',
    storageBucket: 'task-app-f70e1.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmPBhuSlANGO8n9h6pPkMte8OBF9QbJ_s',
    appId: '1:877353420115:ios:03514e63a6eb6ce2574da6',
    messagingSenderId: '877353420115',
    projectId: 'task-app-f70e1',
    storageBucket: 'task-app-f70e1.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoZV6tK5fUsYoZKjm9w7bBVUDiV87sfxA',
    appId: '1:877353420115:web:3fda802f381a9072574da6',
    messagingSenderId: '877353420115',
    projectId: 'task-app-f70e1',
    authDomain: 'task-app-f70e1.firebaseapp.com',
    storageBucket: 'task-app-f70e1.firebasestorage.app',
  );
}
